[package]
name = "arch_installer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terminal-menu = "2.0.4"
ctrlc = "3.2.2"